<div class="jumbotron">
    <h1>欢迎来到 <span class="zf-green">IT技术外文文档翻译平台</span></h1>

    <p>界面有没有很熟悉的感觉？！本站建立时候采用的最新ZF版本<?= \Application\Module::VERSION ?>，后续，本站会尽量的跟上潮流。由于中文文档的缺乏，导致这么优秀的框架在中国的发展特别的low，站长特别的痛心，于是一个idea呼之欲出，就是想利用工作之余的时间，略尽微力，来搭建一个基于后台授权管理的一个众翻平台来抛砖引玉。 </p>
    <p>站长本人就是在一个小厂打工的程序狗，可以说是项目经验基本为零，对git的操作和使用也不是很熟练，此次就是凭着一腔热血，直接开干了，所以希望获得大神们的帮助和指点。</p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/jobsfan/zf3document" target="_blank">前往本站github &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">开发规范</h3>
            </div>
            <div class="panel-body">
                <p>1、缩进4个空格<br />2、函数以及类的左边大括号另起一行写<br />3、函数名类名驼峰式英文命名，禁8级拼音<br />4、类和方法必须注释<br />5、每次git提交，messge写清实现的功能</p>

                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/" target="_blank">前往规范 &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">发展愿景</h3>
            </div>
            <div class="panel-body">
                <p>1、实现acl的后台管理<br />2、基于bootstrap兼容性很强的界面<br />3、ZendFramework的翻译平台<br /><br /></p>

                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank">前往计划 &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">在线支持</h3>
            </div>
            <div class="panel-body">
                <p>
                    QQ1群：213966183<font color=red>（已满）</font><br />
                    QQ2群：527041572（筹建中）<br /><br /><br />
                </p>

                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank">官方IRC支持 &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
