<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">开发规范</h3>
                </div>
                <div class="panel-body">
                    <table class="table table-striped">
                    	<thead>
                            <tr>
                                <th>#</th>
                                <th>规范</th>
                                <th>描述</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>缩进</td>
                                <td>缩进4个空格</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>大括号</td>
                                <td>函数以及类的左边大括号另起一行写</td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>命名</td>
                                <td>函数名类名驼峰式英文命名，禁8级拼音</td>
                            </tr>
                            <tr>
                                <td>4</td>
                                <td>注释</td>
                                <td>类和方法必须注释，要素（功用，参数，返回值，时间，作者）</td>
                            </tr>
                            <tr>
                                <td>5</td>
                                <td>模型</td>
                                <td>一个表对应一个模型，所有关于此单表的逻辑写在这个模型下</td>
                            </tr>
                            <tr>
                                <td>6</td>
                                <td>git</td>
                                <td>每次commit需要messge写清实现的功能</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
		</div>
	</div>
</div>