<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">开发规范</h3>
                </div>
                <div class="panel-body">
                    <p>1、缩进4个空格<br />2、函数以及类的左边大括号另起一行写<br />3、函数名类名驼峰式英文命名，禁8级拼音<br />4、类和方法必须注释<br />5、每次git提交，messge写清实现的功能</p>
                    <p>1、缩进4个空格<br />2、函数以及类的左边大括号另起一行写<br />3、函数名类名驼峰式英文命名，禁8级拼音<br />4、类和方法必须注释<br />5、每次git提交，messge写清实现的功能</p>
                </div>
            </div>
		</div>
	</div>
</div>