<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">开发计划</h3>
                </div>
                <div class="panel-body">
                    <table class="table table-striped">
                    	<thead>
                            <tr>
                                <th>#</th>
                                <th>计划</th>
                                <th>描述</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>把album做一遍</td>
                                <td>熟悉下ZF3的写法</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
		</div>
	</div>
</div>