<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="well well-lg">那些年，踩过的zf3的坑</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<table class="table table-striped">
            	<thead>
                    <tr>
                        <th>#</th>
                        <th>坑</th>
                        <th>描述</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>增加新模块</td>
                        <td>必须要运行<pre>$ composer dump-autoload</pre>$ composer dump-autoload</td>
                    </tr>
                </tbody>
            </table>
		</div>
	</div>
</div>