<div class="container">
	<?= $this->navigation('navigation')
            ->breadcrumbs()
            ->setMinDepth(0)
            ->setPartial('partial/breadcrumb') ?>
	<div class="row">
		<div class="col-md-12">
			<h1>Post Details</h1>

            <dl>
                <dt>Post Title</dt>
                <dd><?= $this->escapeHtml($this->post->getTitle()) ?></dd>
            
                <dt>Post Text</dt>
                <dd><?= $this->escapeHtml($this->post->getText()) ?></dd>
            </dl>
		</div>
	</div>
</div>