<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1><?= $this->escapeHtml($title) ?></h1>
            <p>
                <a href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
            </p>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<table class="table">
                <tr>
                    <th>Title</th>
                    <th>Artist</th>
                    <th>&nbsp;</th>
                </tr>
                <?php foreach ($this->albums as $album) : ?>
                    <tr>
                        <td><?= $this->escapeHtml($album->title) ?></td>
                        <td><?= $this->escapeHtml($album->artist) ?></td>
                        <td>
                            <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
                            <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </table>
		</div>
	</div>
</div>