<div class="container">
	<?= $this->navigation('navigation')
            ->breadcrumbs()
            ->setMinDepth(0)
            ->setPartial('partial/breadcrumb') ?>
	<div class="row">
		<div class="col-md-12">
			<h1>Edit blog post</h1>

            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('blog/edit', [], true));
            echo $this->partial('blog/write/form', [
                'form' => $form,
                'submitLabel' => 'Update post',
            ]);
            ?>
		</div>
	</div>
</div>